//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Ext.CheckpointRules;
    using HP.ST.Ext.CheckpointRules.ArrayCheckpoints;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_StServiceCallActivity16_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Fligh" +
                    "ts_SO_1\\webServices\\Flights_SO\\_5.xsd\" namespace=\"HP.SOAQ.SampleApp/Imports\" /><" +
                    "xs:attribute name=\"fullName\" type=\"xs:string\" /><xs:attribute name=\"group\" type=" +
                    "\"xs:string\" /><xs:attribute name=\"serialize\" type=\"xs:string\" /><xs:attribute na" +
                    "me=\"argType\" type=\"xs:string\" /><xs:element name=\"Envelope\" type=\"Envelope\" /><x" +
                    "s:complexType name=\"Envelope\"><xs:sequence><xs:element minOccurs=\"0\" ref=\"Header" +
                    "\" /><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:sequence><xs:anyAttribute proces" +
                    "sContents=\"lax\" /></xs:complexType><xs:element name=\"Header\" type=\"Header\" /><xs" +
                    ":complexType name=\"Header\"><xs:sequence xmlns=\"\"><xs:any minOccurs=\"0\" maxOccurs" +
                    "=\"unbounded\" processContents=\"lax\" /></xs:sequence><xs:anyAttribute processConte" +
                    "nts=\"lax\" /></xs:complexType><xs:element name=\"Body\" type=\"Body\" /><xs:complexTy" +
                    "pe name=\"Body\"><xs:sequence xmlns=\"\"><xs:element xmlns:q1=\"HP.SOAQ.SampleApp\" re" +
                    "f=\"q1:GetFlightsResponse\" /></xs:sequence><xs:anyAttribute namespace=\"##any\" pro" +
                    "cessContents=\"lax\"><xs:annotation><xs:documentation>Prose in the spec does not s" +
                    "pecify that attributes are allowed on the Body element</xs:documentation></xs:an" +
                    "notation></xs:anyAttribute></xs:complexType><xs:attribute name=\"mustUnderstand\">" +
                    "<xs:simpleType><xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" /></xs:" +
                    "restriction></xs:simpleType></xs:attribute><xs:attribute name=\"actor\" type=\"xs:a" +
                    "nyURI\" /><xs:simpleType name=\"encodingStyle\"><xs:annotation><xs:documentation>\'e" +
                    "ncodingStyle\' indicates any canonicalization conventions followed in the content" +
                    "s of the containing element.  For example, the value \'http://schemas.xmlsoap.org" +
                    "/soap/encoding/\' indicates the pattern described in SOAP specification</xs:docum" +
                    "entation></xs:annotation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType><xs:att" +
                    "ribute name=\"encodingStyle\" type=\"encodingStyle\" /><xs:attributeGroup name=\"enco" +
                    "dingStyle\"><xs:attribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:element n" +
                    "ame=\"Fault\" type=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"><xs:an" +
                    "notation><xs:documentation>Fault reporting structure</xs:documentation></xs:anno" +
                    "tation><xs:sequence><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:element n" +
                    "ame=\"faultstring\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faultactor\"" +
                    " type=\"xs:anyURI\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\" /></xs" +
                    ":sequence></xs:complexType><xs:complexType name=\"detail\"><xs:sequence><xs:any mi" +
                    "nOccurs=\"0\" maxOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" /></xs" +
                    ":sequence><xs:anyAttribute namespace=\"##any\" processContents=\"lax\" /></xs:comple" +
                    "xType></xs:schema>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

        }
        
        private void set_StServiceCallActivity19_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Fligh" +
                    "ts_SO_1\\webServices\\Flights_SO\\_5.xsd\" namespace=\"HP.SOAQ.SampleApp/Imports\" /><" +
                    "xs:attribute name=\"fullName\" type=\"xs:string\" /><xs:attribute name=\"group\" type=" +
                    "\"xs:string\" /><xs:attribute name=\"serialize\" type=\"xs:string\" /><xs:attribute na" +
                    "me=\"argType\" type=\"xs:string\" /><xs:element name=\"Envelope\" type=\"Envelope\" /><x" +
                    "s:complexType name=\"Envelope\"><xs:sequence><xs:element minOccurs=\"0\" ref=\"Header" +
                    "\" /><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:sequence><xs:anyAttribute proces" +
                    "sContents=\"lax\" /></xs:complexType><xs:element name=\"Header\" type=\"Header\" /><xs" +
                    ":complexType name=\"Header\"><xs:sequence xmlns=\"\"><xs:any minOccurs=\"0\" maxOccurs" +
                    "=\"unbounded\" processContents=\"lax\" /></xs:sequence><xs:anyAttribute processConte" +
                    "nts=\"lax\" /></xs:complexType><xs:element name=\"Body\" type=\"Body\" /><xs:complexTy" +
                    "pe name=\"Body\"><xs:sequence xmlns=\"\"><xs:element xmlns:q1=\"HP.SOAQ.SampleApp\" re" +
                    "f=\"q1:CreateFlightOrderResponse\" /></xs:sequence><xs:anyAttribute namespace=\"##a" +
                    "ny\" processContents=\"lax\"><xs:annotation><xs:documentation>Prose in the spec doe" +
                    "s not specify that attributes are allowed on the Body element</xs:documentation>" +
                    "</xs:annotation></xs:anyAttribute></xs:complexType><xs:attribute name=\"mustUnder" +
                    "stand\"><xs:simpleType><xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" " +
                    "/></xs:restriction></xs:simpleType></xs:attribute><xs:attribute name=\"actor\" typ" +
                    "e=\"xs:anyURI\" /><xs:simpleType name=\"encodingStyle\"><xs:annotation><xs:documenta" +
                    "tion>\'encodingStyle\' indicates any canonicalization conventions followed in the " +
                    "contents of the containing element.  For example, the value \'http://schemas.xmls" +
                    "oap.org/soap/encoding/\' indicates the pattern described in SOAP specification</x" +
                    "s:documentation></xs:annotation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType>" +
                    "<xs:attribute name=\"encodingStyle\" type=\"encodingStyle\" /><xs:attributeGroup nam" +
                    "e=\"encodingStyle\"><xs:attribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:el" +
                    "ement name=\"Fault\" type=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"" +
                    "><xs:annotation><xs:documentation>Fault reporting structure</xs:documentation></" +
                    "xs:annotation><xs:sequence><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:el" +
                    "ement name=\"faultstring\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faul" +
                    "tactor\" type=\"xs:anyURI\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\"" +
                    " /></xs:sequence></xs:complexType><xs:complexType name=\"detail\"><xs:sequence><xs" +
                    ":any minOccurs=\"0\" maxOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\"" +
                    " /></xs:sequence><xs:anyAttribute namespace=\"##any\" processContents=\"lax\" /></xs" +
                    ":complexType></xs:schema>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

            // Checkpoint 2
            IVTDGetter actualValueGetter2 = new VTDXPathGetter(new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrderResponse'][1]/*[local-name(.)='CreateFlightOrderResult'][1]/*[local-name(.)='TotalPrice'][1]"), XmlTypeCode.Float, false);
            IVTDSetter actualValueSetter2 = new VTDCheckpointSetter(XmlTypeCode.Float);
            BindDirection actualBindDirection2 = new BindDirection(_flow.StServiceCallActivity19, actualValueGetter2, actualValueSetter2);
            CpValObj valueActualObject2 = new CpValObj(actualBindDirection2, XmlTypeCode.Float, false);
            CpValObj valueExpectedObject2 = new CpValObj("390", XmlTypeCode.Float);
            ValueCPRule cpRule2 = new ValueCPRule(valueActualObject2, valueExpectedObject2, PrimitiveTypeCP.SmallerThanOrEqualTo, "<=", false);
            activity.AddCheckpointRule(cpRule2);

        }
    }
}
